# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Enzo Lagadec
title: Etudiant en 2ème année de BUT Informatique à Annecy
email: enzo.lagadec@etu.univ-savoie.fr
website: https://github.com/nnnnnzo/nnnnnzo.github.io
website_title: src portfolio

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  nnnnnzo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: enzo_eorg
linkedin_username: enzo-lagadec-84b766252
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: A propos de moi
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Je suis Enzo Lagadec et j'ai 19 ans. j'adore le développement informatique, l'intelligence artificielle, le developpement web, et être créatif dans mes projets. Dans ce portfolio, vous verrez un aperçu de mes compétences en informatique et de mes derniers projets. J'espère que vous apprécierez ce que vous verrez et serez intéressé par ce que j'ai fait jusqu'à présent.<br/><br/>
  Mes compétences:<br/>
  ![Mes Skills](https://skillicons.dev/icons?i=html,css,js,swift,cs,php,postgres,bash,laravel,figma,py,linux,raspberrypi,visualstudio,unity)

content:

  - title: Formations # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: BUT Informatique
        link: https://formations.univ-smb.fr/fr/catalogue/but-BUT/sciences-technologies-sante-STS/but-informatique-KGYS5DF3//but2-info-integration-d-applications-et-management-du-systeme-d-information-KI9091VE.html
        link_text: USMB Formation
        caption: Septembre 2021 - Aujourd'hui
        sub_title: IUT d'Annecy
        description: | # this will include new lines to allow paragraphs
          Bachelor Universitaire de Technologie Informatique: <br/>
          Parcours <mark>intégration d'applications et management du système d'information</mark>

      - layout: left
        title: Bacalaureat Général
        caption: 2021
        sub_title: Lycée René Perrin - Ugine
        description: | # this will include new lines to allow paragraphs
          Spécialités: <br/>
          <mark>Sciences de l'ingénieur</mark> <br/>
          <mark>Numérique et sciences de l'informatique</mark>

  - title: Projets # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        title: The Lab Sandbox
        link: https://gamejolt.com/games/Bendythedumbass/485386
        link_text: Site du jeu
        additional_links:
          - title:  nnnnnzo/TheLabSandbox-src
            icon: fab fa-github
            url: https://github.com/nnnnnzo/TheLabSourceScripts
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Le jeu en réseau le plus aberrant que vous ayez jamais vu.
        description: | # this will include new lines to allow paragraphs
          Jeu en réseau développé en C# avec Unity. <br/>
          Le jeu de type bac à sable où vous pouvez faire ce que vous voulez, des serveurs sont disponibles pour jouer avec vos amis ! <br/>
          Disponible sur GameJolt gratuitement sur toutes les plateformes.

      - layout: right
        title: KhaptaPharma
        additional_links:
          - title:  nnnnnzo/KhaptaPharma
            icon: fab fa-github
            url: https://github.com/nnnnnzo/KhaptaPharma
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Projet d'étude de 1ère année:
          Application de gestion de pharmacie développée en C# avec WPF. <br/>
          Fonctionne avec une base de données PostgreSQL. <br/>

      - layout: right
        title: safepeur
        additional_links:
          - title:  nnnnnzo/safepeur
            icon: fab fa-github
            url: https://github.com/nnnnnzo/safepeur
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Projet d'étude de fin de 1ère année:
          Jeu d'horreur développé en C# avec Unity en groupe. <br/>
          Réalisé en 1 semaines. Code source bientôt disponible. <br/>

          

      - layout: right
        title: Nyan Cat Freebox
        link: https://www.universfreebox.com/article/57815/nyan-cat-debarque-gratuitement-sur-les-freebox-revolution-one-et-delta-mais-l-interet-est-assez-limite
        link_text: Article de presse 
        additional_links:
          - title:  nnnnnzo/NyanCatFreebox
            icon: fab fa-github
            url: https://github.com/nnnnnzo/Qt_NC
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          "Nyan Cat débarque gratuitement sur les Freebox Révolution, One et Delta, mais l’intérêt est assez limité"
        description: | # this will include new lines to allow paragraphs
          J'ai mis le Nyan Cat sur toutes les Freebox de France. <br/>
          "Interet limité" mais c'est quand même la classe. <br/>
          ![Nyan gif](https://media.tenor.com/9zmtHZ0tIjkAAAAi/nyancat-rainbow-cat.gif)

  - title: Expériences # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Milimew
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: SAE semestre 3
        caption: Septembre 2022 - Present
        description: | # this will include new lines to allow paragraphs
          Site web de vente de meubles en ligne (from scratch, du MCD jusqu'au site final). <br/>
          Développé en PHP avec le framework Laravel. <br/>
          Fonctionne avec une base de données PostgreSQL. <br/>
          Fonctionnalités: <br/>
          - Inscription / Connexion <br/>
          - Panier <br/>
          - Commande <br/>
          - Favoris <br/>
          - Recherche <br/>
          - Paiement <br/>
          - Cookies <br/>
          - Administration <br/>
          - Gestion des produits <br/>
          - Gestion des utilisateurs <br/>
          - Gestion des commandes <br/>
          - Gestion des catégories <br/>
          - Gestion des promotions <br/>
          - Gestion des avis <br/>
          - Gestion des images <br/>
          - Gestion des stocks <br/>
          - Gestion des statistiques <br/>
          - Gestion des paramètres <br/>
          - Gestion des livraisons <br/>
          - Gestion des adresses <br/>


  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
